// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'featured_content.freezed.dart';
part 'featured_content.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<FeaturedContentInfo>> featuredContent({required String source}) =>
    RustLib.instance.api
        .crateMethodMetadataProviderFeaturedContentFeaturedContent(
            source: source);

@freezed
sealed class FeaturedContentInfo with _$FeaturedContentInfo {
  const factory FeaturedContentInfo({
    required String source,
    required String id,
    required String title,
    required List<String> contextual,
    required String shortDescription,
    required String bannerUrl,
  }) = _FeaturedContentInfo;

  factory FeaturedContentInfo.fromJson(Map<String, dynamic> json) =>
      _$FeaturedContentInfoFromJson(json);
}
