// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../download_provider.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<PinBoxFutureOutputResultOptionDownloadItemValueStringAsyncRecursion>
    getDownload({required DownloadItemKey downloadItemKey}) =>
        RustLib.instance.api.crateMethodDownloadProviderGetDownloadGetDownload(
            downloadItemKey: downloadItemKey);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<:: Pin < Box < Future < Output = Result < Option < DownloadItemValue > , String > > + 'async_recursion + Send > >>>
abstract class PinBoxFutureOutputResultOptionDownloadItemValueStringAsyncRecursion
    implements RustOpaqueInterface {}
