// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../download_provider.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<DownloadItemValue?> getDownload(
        {required String source,
        required String id,
        required BigInt seasonIndex,
        required BigInt episodeIndex}) =>
    RustLib.instance.api.crateMethodDownloadProviderGetDownloadGetDownload(
        source: source,
        id: id,
        seasonIndex: seasonIndex,
        episodeIndex: episodeIndex);
